# ============================================================================================= #
# ORORA_CLI
# ============================================================================================= #

FROM ghcr.io/ublue-os/bluefin-cli:latest

# ================================= #

LABEL maintainer="lecoqjacob@proton.me" \
    com.github.containers.toolbox="true" \
    summary="A cloud-native terminal experience" \
    usage="This image is meant to be used with the toolbox or distrobox command"


# ================================= #

COPY shared/files /
COPY toolboxes/orora-cli/extra-packages toolboxes/orora-cli/programs.sh /

RUN apk update && \
    apk upgrade && \
    grep -v '^#' /extra-packages | xargs apk add && \
    mv /etc/profile.d/00-bluefin-cli-brew-firstrun.sh /etc/profile.d/00-orora-cli-brew-firstrun.sh && \
    sed -i 's/Bluefin/Orora/g; s/bluefin/orora/g' /etc/profile.d/00-orora-cli-brew-firstrun.sh
    # Setup the XDG directories
    # mkdir -p /XDG_DIRS && \
    # mkdir -p /XDG_DIRS/cache && \
    # mkdir -p /XDG_DIRS/config && \
    # mkdir -p /XDG_DIRS/local/share && \
    # mkdir -p /XDG_DIRS/local/state

RUN \
    # mv /orora-nvim /XDG_DIRS/config/nvim && \
    # nvim --headless "+Lazy! sync" +qa && \
    # chmod -R o+rwx /XDG_DIRS/ && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/ujust && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/flatpak && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/distrobox && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/code && \
    /programs.sh

# Add .cargo/bin to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

RUN rm /extra-packages /programs.sh
