# ============================================================================================= #
# ORORA_CLI
# ============================================================================================= #

FROM ghcr.io/ublue-os/bluefin-cli:latest

# ================================= #

LABEL maintainer="lecoqjacob@proton.me" \
    com.github.containers.toolbox="true" \
    summary="A cloud-native terminal experience" \
    usage="This image is meant to be used with the toolbox or distrobox command"


# ================================= #

COPY shared/files /
COPY toolboxes/orora-cli/extra-packages toolboxes/orora-cli/programs.sh /

RUN apk update && \
    apk upgrade && \
    grep -v '^#' /extra-packages | xargs apk add && \
    mv /etc/profile.d/00-bluefin-cli-brew-firstrun.sh /etc/profile.d/00-orora-cli-brew-firstrun.sh && \
    sed -i 's/Bluefin/Orora/g; s/bluefin/orora/g' /etc/profile.d/00-orora-cli-brew-firstrun.sh

RUN \
    # LINK LOCAL
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/code && \
    # LINK BIN
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/ujust && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/wl-copy && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/flatpak && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/distrobox && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/gpg-agent && \
    ln -fs /usr/bin/distrobox-host-exec /usr/bin/pinentry-gnome3 && \
    /programs.sh

RUN rm /extra-packages /programs.sh
