name: Build and Push Image

on:
  schedule:
    - cron: "0 6 * * *" # at 06:00 UTC (midnight CST)

  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"

  push:
    branches:
      - main
      - testing
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**.md"

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

env:
  IMAGE_VARIANT: main
  DOCKER_BUILDKIT: 1
  BUILDX_EXPERIMENTAL: 1
  FEDORA_MAJOR_VERSION: 39

jobs:
  run-build:
    name: Build and Push Orora Image
    runs-on: ubuntu-22.04
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        toolbox_name: ["orora-cli", "wolfi-toolbox", "wolfi-dx-toolbox"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Containerfile path
        shell: bash
        run: |
          #!/bin/bash

          TOOLBX="orora-cli"
          if "${TOOLBX}" ~= "wolfi"; then
            TOOLBX="wolfi-toolbox"
          fi

          echo "CONTAINERFILE_PATH=./toolboxes/${TOOLBX}/Containerfile" >> $GITHUB_ENV

      - name: Build and Deploy image
        uses: bayou-brogrammer/deploy-container-action@main
        with:
          support: latest
          push_container: "true"
          target: ${{ matrix.toolbox_name }}
          file: ${{ env.CONTAINERFILE_PATH }}
          image_name: ${{ matrix.toolbox_name }}
          image_variant: ${{ env.IMAGE_VARIANT }}
          version: ${{ env.FEDORA_MAJOR_VERSION }}
          signing_key: ${{ secrets.SIGNING_SECRET }}
          container_registry: ghcr.io/${{ github.repository_owner }}
        env:
          CONTAINERFILE_PATH: ${{ env.CONTAINERFILE_PATH }}
